# Infos

* Professeur: Anna Lachowska


## Sujets

* Nbr reel
* Nbr complexes
* Suites numeriques
* Fonctions
* Lim continuité
* Derivé
* Etude de fc
* Series, poly taylor
* Intégrales def., undef.
* Intégrales impropres (mdr)


## Literature

* Calcul differentiel et intégral, Jacques douchet et Bruno Zwahlen
* Recueil d'exercice et aide memoire, Jacques Douchet
* Concepts et contextes

## Exercices

* Resulats 2-3 jours après

## Examens

* partie commune 80%
	- QCM.
	- Points négatifs
* partie spécifique 20%
	- DEV.
* sans calc., sans doc, sans aides mémoires


# Prérequis

* Identité algébrique
	* polynomiales:
	  	- $(x+y)^2$
		- $(x-y)^3 = (x-y)(x^2+xy+y^2)$
		- $(x+y)^3 = (x+y)(x^2-xy+y^2)$
* Exponentielles
	* $a^xa^y = a ^{x+y}$
	* toutes les prop. exp. (cf. aide memoire)
* Log
	* toute les props. log. (cf. aide memoire)
	* $log$ pour $\log_e()$
* Trig
	* Toutes les props trig (cf. aide memoire)
	* tgx(x) ctg(x)
	* Identités
		* $\sin(x+-y)=\sin(x)\cos(y)\pm\cos(x)\sin(y)$
		* $\cos(x+-y)=\cos(x)\cos(y)\mp\sin(x)\sin(y)$
		* $1 = \sin(x)^2 + \cos(x)^2$
	* Valeurs de sin cos à savoir
		* $\pi/6,\pi/4;\pi/3,\pi/2,\pi,0$
* Function
	* Ex. $f(x)=3x^2+2x+1$
	* Types de function
	  	* Polynomiales
			* $f(x)=a_nx^n+a_{n-1}x^{n-1}+...+a_n$, $a \in \mathbb{R}$
			* Linéaire
			* Quadratique
			* Etc.
		* Rationnelles
			* polynome sur polynome
			* $\frac{P(x)}{Q(x)}$ $Q(x) \neq 0$
			* $D_f \in \mathbb{R} \setminus f(x)=0$
		* Algébriques
		  	* Functions appartenus de polynomes avec $+,-,/,\sqrt{}$
			* Ex. $f(x)=\sqrt{x}$
		* Transendantes
			* Fc Trigo et réciproques
				* Ex. $\cos(x)$ $\sin(x)$ $\cot(x)$ $\tan()$
			* Fc log., exp.
				* $f(x) = e^x$
			  	* $f(x) = \log(x)$
				* $\log(e^x) = x, x \in \mathbb{R}$ 
				* Ex. $f(x) = a^x$ réc: $g(x) = \log_a(x), a \in \mathbb{R}^+$

* Tranformation des graphiques
	* $x^2 - 3$
		* $-3y$ depuis $x^2$
	* $(x-3)^2$
	  	* $+3x$ depuis $x^2$
	* $2\sin(x)$
	  	- x2 verticale
	* $\sin(2x)$
		- 1/2 période
